test: fix beforeEach for yeoman-test v1.6.0
`run_context` is now a generator **and** a promise, which caused:

```
Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
```